name: Build and push tidybee-hub images to ghcr.io

on:
  push:
    branches:
      - main
    paths-ignore:
      - .devcontainer/
      - "**.md"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-matrix:
    if: github.repository == 'tidybee/tidybee-hub' && github.ref == 'refs/heads/main'
    strategy:
      fail-fast: false
      matrix:
        service: [ApiGateway, Auth, DataProcessing, TidyEvents]
        include:
          - service_name: api-gateway
            service: ApiGateway
          - service_name: auth
            service: Auth
          - service_name: data-processing
            service: DataProcessing
          - service_name: events
            service: TidyEvents

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v1

      - name: Fetch metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: tidybee/tidybee-hub-${{ matrix.service_name }}

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8
          file: ${{ matrix.service }}/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ steps.metadata.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
