name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-latest, windows-latest, macos-latest]
            include:
              - os: ubuntu-latest
                dotnet-rid: linux-x64
              - os: windows-latest
                dotnet-rid: win-x64
              - os: macos-latest
                dotnet-rid: osx-x64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore deps
        run: dotnet publish -c Release -o ./publish -r ${{ matrix.dotnet-rid }} --self-contained -p:PublishReadyToRun=true

      - name: Debug publish folder
        shell: bash
        run: ls -lRa ./publish
