name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-latest, windows-latest, macos-latest]
            project: ["ApiGateway", "Auth", "DataProcessing", "TidyEvents"]
            include:
              - os: ubuntu-latest
                dotnet-rid: linux-x64
              - os: windows-latest
                dotnet-rid: win-x64
              - os: macos-latest
                dotnet-rid: osx-x64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore deps
        run: dotnet publish ${{ matrix.project }}/${{ matrix.project }}.csproj -c Release -o ./publish/${{ matrix.project }}  -r ${{ matrix.dotnet-rid }} -p:PublishSingleFile=true --self-contained

      - name: Debug publish folder
        shell: bash
        run: ls -lRa ./publish


      - name: Archive all folders
        run: |
          for d in ./publish/*; do
            echo "Archiving $d"
            zip -r $d.zip $d
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.project }}.zip
      
